version: "3.9"
services:
  cooperative:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo/db_assembly
    networks:
      - backend
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - backend
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    networks:
      - backend
networks:
  backend:
    driver: bridge